### ISSUE TITLE
error during start

### ISSUE THREAD

**Issue by mrsalieri** [emregeldegul/tfc#2]
Sorry for interrupting again, but I have got a new error during start. Again, I want to mention that I am not familiar with python so it may be my fault. Thanks.

TFC listens To Your Clipboard For Translation.
==================================================
Traceback (most recent call last):
  File "/usr/local/bin/tfc", line 11, in <module>
    load_entry_point('tfc==0.1.0', 'console_scripts', 'tfc')()
  File "/usr/local/lib/python3.7/site-packages/tfc-0.1.0-py3.7.egg/tfc/__init__.py", line 23, in main
  File "/usr/local/lib/python3.7/site-packages/tfc-0.1.0-py3.7.egg/tfc/tfc.py", line 36, in start
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'notify-send': 'notify-send'

**Comment by emregeldegul** [comment]
It gives an error because there is no notify-send program on mac-os.
Can you reach me on telegram for Mac-Os tests?

@emregeldegul

**Comment by emregeldegul** [comment]
TFC now support the Mac-Os with this commit.

[code refactoring](https://github.com/emregeldegul/tfc/commit/134bcf4ce37e58ad41543a5dc0ecfe1ae258f630)
